repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: detect-private-key
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: trailing-whitespace

-   repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.8.1
    hooks:
    - id: terraform_docs
    - id: terraform_fmt
    - id: terraform_validate_no_variables

-   repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.13.0
    hooks:
    -   id: markdownlint
