repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: detect-private-key
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: trailing-whitespace

-   repo: git://github.com/kintoandar/pre-commit.git
    sha: v2.1.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate

-   repo: git://github.com/igorshubovych/markdownlint-cli
    sha: v0.5.0
    hooks:
    -   id: markdownlint
