repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.1
    hooks:
      - id: markdownlint

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.31.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt

  - repo: git://github.com/golangci/golangci-lint
    rev: v1.27.0
    hooks:
      - id: golangci-lint
